version: "2"
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    command:
      npm run dev-start
    links:
      - mysql:mysql_master
      - redis:redis

  mysql:
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  redis:
    image: redis:2.8
    volumes:
      - ./data/redis:/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql:db
    ports:
      - 8080:80
    environment:
      - MYSQL_ROOT_PASSWORD=''
